on:
  push:
    branches:
      - main
  pull_request:
name: test
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
          cache: false
      - id: cache-path
        run: |
          echo "mod=$(go env GOMODCACHE)" >> $GITHUB_OUTPUT
          echo "build=$(go env GOCACHE)" >> $GITHUB_OUTPUT
      - uses: actions/cache/restore@v3
        id: cache-restore-mod
        with:
          path: ${{ steps.cache-path.outputs.mod }}
          key: ${{ github.workflow}}-${{ github.job }}-${{ runner.os }}-mod-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ github.workflow}}-${{ github.job }}-${{ runner.os }}-mod-
      - uses: actions/cache/restore@v3
        with:
          path: ${{ steps.cache-path.outputs.build }}
          key: ${{ github.workflow}}-${{ github.job }}-${{ runner.os }}-build
      - name: Print job and workflow information
        run: |
          echo "Workflow ID: ${{ github.workflow }}"
          echo "Run ID: ${{ github.run_id }}"
          echo "Run Number: ${{ github.run_number }}"
          echo "Job ID: ${{ github.job }}"

      # - uses: actions/cache/restore@v3
      #   with:
      #     path: ${{ steps.cache-path.outputs.build }}
      - name: Run tests
        run: make test
      - uses: actions/cache/save@v3
        if: github.ref == 'refs/heads/main' && steps.cache-restore-mod.outputs.cache-hit != 'true'
        with:
          key: ${{ github.workflow}}-${{ github.job }}-${{ runner.os }}-mod-${{ hashFiles('**/go.sum') }}
          path: ${{ steps.cache-path.outputs.mod }}
      - uses: actions/cache/save@v3
        if: github.ref == 'refs/heads/main'
        with:
          key: ${{ github.workflow}}-${{ github.job }}-${{ runner.os }}-build
          path: ${{ steps.cache-path.outputs.build }}
